### ISSUE TITLE
custom_js needs loaded in customiser

### ISSUE THREAD

**Issue by alasdaircr** [faktorvier/f4-media-taxonomies#1]
Following line needs added to `FT\MT\Core\Hooks::init()`

`add_action('customize_controls_enqueue_scripts', __NAMESPACE__ . '\\Hooks::add_custom_js');`

otherwise selecting images is broken in the customiser.

**Comment by Stibo** [comment]
@alasdaircr Thanks for your feedback! Now the media selector should work in the customizer too.
