### ISSUE TITLE
PHP closing tags

### ISSUE THREAD

**Issue by szepeviktor** [faktorvier/f4-media-taxonomies#2]
Hello! Your nice code repels the closing PHP tag at EOF.

PSR says _The closing `?>` tag MUST be omitted from files containing only PHP._
https://www.php-fig.org/psr/psr-2/#22-files

Would you welcome a PR removing all of them?

**Comment by Stibo** [comment]
Thanks for your feedback. We removed all the closing tags from php only files.

**Comment by szepeviktor** [comment]
You're welcome.
